from __future__ import annotations

from datetime import date, datetime
import json
import logging
from typing import Any

import psycopg
from psycopg.rows import dict_row

from app.config import settings


def to_jsonable_row(row: dict[str, Any] | None) -> dict[str, Any] | None:
    """Convert PostgreSQL row values into MCP JSON-safe values."""

    if row is None:
        return None

    safe_row: dict[str, Any] = {}
    for key, value in row.items():
        if isinstance(value, (date, datetime)):
            safe_row[key] = value.isoformat()
        else:
            safe_row[key] = value
    return safe_row


class TicketRepository:
    """PostgreSQL access layer for support tickets."""

    def get_connection(self) -> psycopg.Connection:
        """Open a PostgreSQL connection using the Docker Compose database URL."""

        return psycopg.connect(settings.database_url, row_factory=dict_row)

    def create_ticket(
        self,
        customer_email: str,
        description: str,
        detected_objects: list[str],
    ) -> dict[str, Any]:
        """Create a new support ticket after image analysis."""

        detected_error_code = next((item for item in detected_objects if item.startswith("E-")), None)
        logging.info("db | insert ticket email=%s error_code=%s", customer_email, detected_error_code)
        with self.get_connection() as conn:
            with conn.cursor() as cur:
                cur.execute(
                    """
                    INSERT INTO support_tickets (
                        customer_email,
                        status,
                        description,
                        detected_objects,
                        detected_error_code
                    )
                    VALUES (%s, %s, %s, %s::jsonb, %s)
                    RETURNING *
                    """,
                    (
                        customer_email,
                        "image_analyzed",
                        description,
                        json.dumps(detected_objects),
                        detected_error_code,
                    ),
                )
                row = to_jsonable_row(dict(cur.fetchone()))
                logging.info("db | inserted ticket_id=%s", row["id"])
                return row

    def attach_technical_steps(self, ticket_id: int, technical_steps: str) -> dict[str, Any]:
        """Store troubleshooting steps generated by the technical assistant."""

        with self.get_connection() as conn:
            with conn.cursor() as cur:
                cur.execute(
                    """
                    UPDATE support_tickets
                    SET technical_steps = %s,
                        status = %s
                    WHERE id = %s
                    RETURNING *
                    """,
                    (technical_steps, "technical_steps_added", ticket_id),
                )
                row = to_jsonable_row(dict(cur.fetchone()))
                logging.info("db | technical steps saved ticket_id=%s", ticket_id)
                return row

    def mark_email_sent(self, ticket_id: int, subject: str, body: str) -> dict[str, Any]:
        """Mark a ticket completed after the email tool sends a reply."""

        with self.get_connection() as conn:
            with conn.cursor() as cur:
                cur.execute(
                    """
                    UPDATE support_tickets
                    SET reply_subject = %s,
                        reply_body = %s,
                        email_sent = TRUE,
                        status = %s,
                        completed_at = NOW()
                    WHERE id = %s
                    RETURNING *
                    """,
                    (subject, body, "completed", ticket_id),
                )
                row = to_jsonable_row(dict(cur.fetchone()))
                logging.info("db | marked email sent ticket_id=%s", ticket_id)
                return row

    def get_ticket(self, ticket_id: int) -> dict[str, Any] | None:
        """Fetch one ticket by ID."""

        with self.get_connection() as conn:
            with conn.cursor() as cur:
                cur.execute("SELECT * FROM support_tickets WHERE id = %s", (ticket_id,))
                row = cur.fetchone()
                logging.info("db | get ticket_id=%s found=%s", ticket_id, bool(row))
                return to_jsonable_row(dict(row)) if row else None

    def latest_ticket_for_email(self, customer_email: str) -> dict[str, Any] | None:
        """Fetch the most recent ticket for a customer email."""

        with self.get_connection() as conn:
            with conn.cursor() as cur:
                cur.execute(
                    """
                    SELECT *
                    FROM support_tickets
                    WHERE customer_email = %s
                    ORDER BY created_at DESC
                    LIMIT 1
                    """,
                    (customer_email,),
                )
                row = cur.fetchone()
                logging.info("db | latest ticket email=%s found=%s", customer_email, bool(row))
                return to_jsonable_row(dict(row)) if row else None
